## **Imported libraries**

In [14]:
import random
import numpy as np

## **Matrix Product**

In [15]:
def MatrixProduct(A, B, C, n):
  for i in range(n):
    for j in range(n):
      C[i, j] = np.dot(A[i], B[:,j])

# **Testing Block**
Let's test `MatrixProduct` with `n=5`.

In [16]:
n = 5

A = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
B = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
C = np.array([[0 for _ in range(n)] for _ in range(n)])
MatrixProduct(A, B, C, n)
print(f'Matrix A:\n{A}\n')
print(f'Matrix B:\n{B}\n')
print(f'AxB:\n{C}\n')

Matrix A:
[[  1   8   5  -4   8]
 [  0   4   8   4   5]
 [  6   2 -10   5  -1]
 [  5   1 -10   8 -10]
 [ -9   4   0   5   4]]

Matrix B:
[[ 7 -8  6  9 -6]
 [-3 -1 -3 -4 -1]
 [ 8  4  1 -1  2]
 [ 0  7  4  0  9]
 [-7  8  7 -8 -1]]

AxB:
[[ -33   40   27  -92  -48]
 [  17   96   47  -64   43]
 [ -37  -63   33   64  -12]
 [  22 -105  -21  131   31]
 [-103  135  -18 -129   91]]



# **Algorithm Correctness Verification**
We show that the algorithm works correctly (product) compared to a well-known function within numpy: `np.matmul(A, B)`. We multiply `m=1000000` different matrixes (of size `n=5`).

In [12]:
m = 1000000
n = 4
test = 0
for _ in range(m):
  A = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
  B = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
  C = np.array([[0 for _ in range(n)] for _ in range(n)])
  MatrixProduct(A, B, C, n)
  D = np.matmul(A, B)
  test += np.array_equal(C, D)
print(test == m) #If the test is True, the MatrixProduct algorithm works correctly.

True
