## **Libraries imported**

In [1]:
import random
import numpy as np

## **Recursive Matrix Multiplication**

In [2]:
def RecursiveProduct(A, B, C, n):
  if n == 1:
    C[0][0] += A[0][0] * B[0][0]
    return

  half = n//2

  A11 = A[:half, :half]
  A12 = A[:half, half:]
  A21 = A[half:, :half]
  A22 = A[half:, half:]

  B11 = B[:half, :half]
  B12 = B[:half, half:]
  B21 = B[half:, :half]
  B22 = B[half:, half:]

  C11 = C[:half, :half]
  C12 = C[:half, half:]
  C21 = C[half:, :half]
  C22 = C[half:, half:]

  RecursiveProduct(A11, B11, C11, half)
  RecursiveProduct(A12, B21, C11, half)

  RecursiveProduct(A11, B12, C12, half)
  RecursiveProduct(A12, B22, C12, half)

  RecursiveProduct(A21, B11, C21, half)
  RecursiveProduct(A22, B21, C21, half)

  RecursiveProduct(A21, B12, C22, half)
  RecursiveProduct(A22, B22, C22, half)

  C[:half, :half] = C11
  C[:half, half:] = C12
  C[half:, :half] = C21
  C[half:, half:] = C22

# **Testing Block**
Let's test `RecursiveProduct` with `n=4`.

In [4]:
n = 4

A = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
B = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
C = np.array([[0 for _ in range(n)] for _ in range(n)])
RecursiveProduct(A, B, C, n)
print(f'Matrix A:\n{A}\n')
print(f'Matrix B:\n{B}\n')
print(f'AxB:\n{C}\n')

Matrix A:
[[ -9  -2  10   1]
 [ -6  -5 -10   6]
 [  2 -10   9  -9]
 [ -7  -5   2   7]]

Matrix B:
[[ -5   4  10   5]
 [ -3  -1   6   4]
 [ -8  -9  -7   4]
 [  3 -10  -4   6]]

AxB:
[[ -26 -134 -176   -7]
 [ 143   11  -44  -54]
 [ -79   27  -67  -48]
 [  55 -111 -142   -5]]



# **Algorithm Correctness Verification**
We show that the algorithm works correctly (product) compared to a well-known function within numpy: `np.matmul(A, B)`. We multiply `m=1000000` different matrixes (of size `n=4`).

In [5]:
m = 1000000
n = 4
test = 0
for _ in range(m):
  A = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
  B = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
  C = np.array([[0 for _ in range(n)] for _ in range(n)])
  RecursiveProduct(A, B, C, n)
  D = np.matmul(A, B)
  test += np.array_equal(C, D)
print(test == m) #If the test is True, the RecursiveProduct algorithm works correctly.

True
