## **Imported libraries**

In [4]:
import random
import numpy as np

## **Strassen's Multiplication**

In [5]:
def Strassen(A, B, C, n):
    if n == 1:
        C[0, 0] = A[0, 0] * B[0, 0]
        return

    half = n // 2

    A11, A12, A21, A22 = A[:half, :half], A[:half, half:], A[half:, :half], A[half:, half:]
    B11, B12, B21, B22 = B[:half, :half], B[:half, half:], B[half:, :half], B[half:, half:]
    C11, C12, C21, C22 = C[:half, :half], C[:half, half:], C[half:, :half], C[half:, half:]

    M1 = np.zeros((half, half))
    M2 = np.zeros((half, half))
    M3 = np.zeros((half, half))
    M4 = np.zeros((half, half))
    M5 = np.zeros((half, half))
    M6 = np.zeros((half, half))
    M7 = np.zeros((half, half))

    Strassen(A11 + A22, B11 + B22, M1, half)
    Strassen(A21 + A22, B11, M2, half)
    Strassen(A11, B12 - B22, M3, half)
    Strassen(A22, B21 - B11, M4, half)
    Strassen(A11 + A12, B22, M5, half)
    Strassen(A21 - A11, B11 + B12, M6, half)
    Strassen(A12 - A22, B21 + B22, M7, half)

    C11[:, :] = M1 + M4 - M5 + M7
    C12[:, :] = M3 + M5
    C21[:, :] = M2 + M4
    C22[:, :] = M1 - M2 + M3 + M6

# **Testing Block**
Let's test `Strassen` with `n=4`.

In [6]:
n = 4

A = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
B = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
C = np.array([[0 for _ in range(n)] for _ in range(n)])
Strassen(A, B, C, n)
print(f'Matrix A:\n{A}\n')
print(f'Matrix B:\n{B}\n')
print(f'AxB:\n{C}\n')

Matrix A:
[[ 5 -4 -8 -8]
 [-8  3 10 -5]
 [10  7  2 10]
 [-3 -9  6  6]]

Matrix B:
[[  1   9   1 -10]
 [ 10   9   4   8]
 [  6  10   0   9]
 [  2  -7   9  -4]]

AxB:
[[ -99  -15  -83 -122]
 [  72   90  -41  214]
 [ 112  103  128  -66]
 [ -45  -90   15  -12]]



# **Algorithm Correctness Verification**
We show that the algorithm works correctly (product) compared to a well-known function within numpy: `np.matmul(A, B)`. We multiply `m=1000000` different matrixes (of size `n=4`).

In [7]:
m = 1000000
n = 4
test = 0
for _ in range(m):
  A = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
  B = np.array([[random.randint(-10, 10) for _ in range(n)] for _ in range(n)])
  C = np.array([[0 for _ in range(n)] for _ in range(n)])
  Strassen(A, B, C, n)
  D = np.matmul(A, B)
  test += np.array_equal(C, D)
print(test == m) #If the test is True, the Strassen's algorithm works correctly.

True
